docker-compose.yml:
services:
  app:
    build: .
    command: poetry run start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    hostname: db
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: bebrasus69
      MYSQL_DATABASE: se_backend
      LC_ALL: C.UTF-8
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

Dockerfile:
FROM python:3.10-slim
EXPOSE 8000
# Установите рабочую директорию
WORKDIR /app

# Установите зависимости из файла poetry.lock
COPY poetry.lock pyproject.toml /app/
RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev

# Скопируйте все файлы в рабочую директорию
COPY . /app

# Установите переменные окружения
ENV MYSQL_DATABASE=se_backend \
    MYSQL_USER=root \
    MYSQL_PASSWORD=bebrasus69 \
    MYSQL_HOST=db \
    MYSQL_PORT=3306

# Запустите сервер FastAPI
CMD ["poetry", "run", "start"]

подключение к бд в SQLAlchemy:
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

from config import \
(
    dbtype, dbdriver, dbuser, 
    dbpassword, dbhost, dbname
)


SQLALCHEMY_DATABASE_URL = "mysql+pymysql://root:bebrasus69@db/se_backend?charset=utf8mb4"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL, connect_args={}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

ошибка: app_1  | sqlalchemy.exc.DataError: (pymysql.err.DataError) (1366, "Incorrect string value: '\\xD0\\xB1\\xD0\\xBB\\xD0\\xB0...' for column 'text' at row 1")
app_1  | [SQL: INSERT INTO publications (title, text, description, owner_id) VALUES (%(title)s, %(text)s, %(description)s, %(owner_id)s)]
app_1  | [parameters: {'title': 'bebratitle', 'text': 'бла бла бла бла про привет мир хелоу врорлд', 'description': 'Привет, Мир!', 'owner_id': 1}]
app_1  | (Background on this error at: https://sqlalche.me/e/20/9h9h)

